### ISSUE TITLE
Map.Clone should return the same type and not base type of Map

### ISSUE THREAD

**Issue by WraithNath** [FaronBracy/RogueSharp#25]
Im subclassing the Map class and using the CaveMapCreationStrategy, during the point of CellularAutomataBigAreaAlgorithm the map is cloned and cast as the type specified in the IMapCreationStrategy interface. however this clone returns null and throws a null reference exception.

I think the clone method should create a new T() rather than a new Map()

For example, this will throw the error:

```
public class CavesMap : Map
{
}

void Test()
{
CaveMapCreationStrategy<CavesMap> strategy = new CaveMapCreationStrategy<CavesMap>(width, height, 40, 4, 3);

CavesMap map = strategy.CreateMap();
}



```

**Comment by FaronBracy** [comment]
Thanks for reporting the issue. I have a potential fix in this commit https://github.com/FaronBracy/RogueSharp/pull/26/commits/ea454e7a33bf4c9349af0b1b4642bad730fe5ccf.

I'll have a pre-release NuGet package soon which will include this change.

**Comment by FaronBracy** [comment]
The pre-release NuGet package is available now.
https://www.nuget.org/packages/RogueSharp/5.0.0-pre

Let me know how this works for you.

**Comment by WraithNath** [comment]
Thanks, I have given that package a try and it seems to have resolved the null reference exception I was getting when calling CreateMap on the MapCreationStrategy.

Great work on the library!
